version: "3.9"

services:
  appium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appium-server
    ports:
      - "4723:4723"
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    command: >
      sh -c "
        LOGDATE=$(date +\"%Y-%m-%d\") &&
        adb kill-server &&
        adb start-server &&
        exec appium
          --allow-insecure uiautomator2:chromedriver_autodownload
          --log-timestamp
          --relaxed-security
          >> /logs/appium_${LOGDATE}.log 2>&1
      "
